- alias: 'Телеграм: Домофон. Управление'
  description: Управление домофоном через телеграм
  trigger:
  - platform: event
    event_type: telegram_callback
    event_data: {}
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == ''/domofon'' }}'
      sequence:
      - service: telegram_bot.send_message
        data:
          target: '{{ trigger.event.data.chat_id }}'
          message: &msg |
            {{'\U00002699'}} **Режим работы домофона**
#Клавиатура
          inline_keyboard: &keyb
          - '{% set domofon_modes = states("select.smartintercom_e8db849c6ee5_modes") %}
             {% if domofon_modes == "Не активен" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Не активен:/domofon_not_active,
             {% set domofon_modes = states("select.smartintercom_e8db849c6ee5_modes") %}
             {% if domofon_modes == "Открывать всегда" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Открывать всегда:/domofon_open_always'
          - '{% if is_state("switch.smartintercom_e8db849c6ee5_mute", "on") %} {{"🟢"}}
             {% else %} {{"🔴"}} 
             {% endif %}
             Беззвучный режим:/domofon_mute,
             {% set domofon_modes = states("select.smartintercom_e8db849c6ee5_modes") %}
             {% if domofon_modes == "Сброс вызова" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Сброс вызова:/domofon_reset_call'
          - '{% set domofon_modes = states("select.smartintercom_e8db849c6ee5_modes") %}
             {% if domofon_modes == "Сброс вызова если нет ответа" %} {{"🟢"}}
             {% else %} {{"🔴"}}
             {% endif %} 
             Сброс вызова если нет ответа:/domofon_resetting_call_no_response'
          - Назад:/backhome

#Кнопка №1. Не активен
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_not_active" }}'
      sequence:
      - service: select.select_option
        data:
          option: Не активен
        target:
          entity_id: select.smartintercom_e8db849c6ee5_modes
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №2. Открывать всегда
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_open_always" }}'
      sequence:
      - service: select.select_option
        data:
          option: Открывать всегда
        target:
          entity_id: select.smartintercom_e8db849c6ee5_modes
    #   - service: input_select.select_option
    #     target:
    #       entity_id: select.smartintercom_e8db849c6ee5_modes
    #     data:
    #       option: Открывать всегда
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №3. Беззвучный режим
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_mute" }}'
      sequence:
      - service: switch.toggle
        # target:
        entity_id: switch.smartintercom_e8db849c6ee5_mute
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №4. Сброс вызова
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_reset_call" }}'
      sequence:
      - service: select.select_option
        target:
          entity_id: select.smartintercom_e8db849c6ee5_modes
        data:
          option: Сброс вызова
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb

#Кнопка №5. Сброс вызова если нет ответа
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.command == "/domofon_resetting_call_no_response" }}'
      sequence:
      - service: select.select_option
        target:
          entity_id: select.smartintercom_e8db849c6ee5_modes
        data:
          option: Сброс вызова если нет ответа
      - delay:
          milliseconds: 300
      - service: telegram_bot.edit_message
        data:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.user_id }}'
          callback_query_id: '{{ trigger.event.data.id }}'
          message: *msg
          inline_keyboard: *keyb
    default: []
  mode: restart

