# ##################################
# System - Power Meter Daily
# ##################################
- alias: system_power_meter_daily
#  id: system_power_meter_daily
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:00'
  action:
#   - service: input_number.set_value
#     # target:
#     data:
#       entity_id: input_number.power_meter_t1
#       value: "{{ ((states('input_number.power_meter_t1')) | float + states('sensor.energy_daily_kvartira_day')|float/1 )|round(2) }}"
#   - service: input_number.set_value
#     # target:
#     data:
#       entity_id: input_number.power_meter_t2
#       value: "{{ ((states('input_number.power_meter_t2')) | float + states('sensor.energy_daily_kvartira_night')|float/1 )|round(2) }}"
  - service: mqtt.publish
    data:
      topic: 'utility/main/energy/day'
      payload: "{{ ((states('sensor.t1')) | float + state_attr('sensor.energy_daily_kvartira_day', 'last_period')|float/1 )|round(2) }}"
      retain: true
  - service: mqtt.publish
    data:
      topic: 'utility/main/energy/night'
      payload: "{{ ((states('sensor.t2')) | float + state_attr('sensor.energy_daily_kvartira_night', 'last_period')|float/1 )|round(2) }}"
      retain: true
  - service: notify.telegram_id_1
    data:
      message: '"\U0001f50c Данные счетчика электричества обновлены!"'

