homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 81
  unit_system: metric
  time_zone: Asia/Yekaterinburg
  country: RU
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
  allowlist_external_dirs:
    - "/config"
    - "/tmp"
    - "/share"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

frontend:
  themes: !include_dir_merge_named themes

api:

websocket_api:

mobile_app:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.88.0/24
    - 172.22.0.0/24
#    - 127.0.0.1

mqtt:
  sensor:
    - name: t1
      state_topic: "utility/main/energy/day"
      unit_of_measurement: "кВт"
      device_class: energy
      # retain: true
    - name: t2
      state_topic: "utility/main/energy/night"
      unit_of_measurement: "кВт"
      device_class: energy
      # retain: true
    - name: Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless

hacs:
  token: !secret hacs_token
  appdaemon: true
  python_script: true
  theme: true

#Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight: !include includes/yeelight.yaml
light: !include includes/light.yaml
notify: !include notify.yaml
camera: !include includes/camera.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
lovelace: !include includes/lovelace.yaml
automation old: !include automations.yaml
switch: !include includes/switch.yaml
#klipper: !include includes/klipper.yaml
alert: !include includes/alert.yaml
utility_meter: !include includes/utility_meter.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
binary_sensor: !include_dir_merge_list includes/binary_sensor
template: !include_dir_merge_list includes/templates


yandex_station:
  username: igorponomarev1986
  password: password_yandex
  include:
    - media_player.samsung_tv_zal
    - media_player.tv_kukhnia

wake_on_lan:

smartir:

#Media Players
media_player:
  - platform: smartir
    name: Samsung tv zal
    unique_id: samsung_tv_zal
    device_code: 2000
    controller_data: remote.mi_remote
    power_sensor: binary_sensor.tv_zal_status #откуда считывать состояния устройства, например с умной розетки

  - platform: smartir
    name: LG tv spalnya
    unique_id: lg_tv_spalnya
    device_code: 1040
    controller_data: remote.ir_broadlink_remote
    power_sensor: binary_sensor.tv_spalnya_status #откуда считывать состояния устройства, например с умной розетки

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_allowed_chat_id1
      - !secret telegram_bot_allowed_chat_id2
      - !secret telegram_bot_allowed_chat_id3

counter:
#  garage_counter:
#    initial: 0
#    step: 1

start_time:

ios:

sun:

logbook:
  exclude:
    entities:
      - automation.garage_door_couter
      - counter.garage_counter
      - input_boolean.garage_door_direction
      - input_boolean.garage_door_motion
      - script.garage_counter_decrement
      - script.garage_counter_increment
      - script.garage_door_direction
      - script.garagescript
      - sensor.garage_open_close
      - automation.kalibrovka_otkryty
      - automation.kalibrovka_zakryty
      - automation.smena_napravleniia
      - script.noop
      - script.zavod_garagescript
      - counter.zavod_garage_counter
      - input_boolean.zavod_garage_door_direction
      - input_boolean.zavod_garage_door_motion
      - script.zavod_garage_counter_decrement
      - script.zavod_garage_counter_increment
      - script.zavod_garage_door_direction
      - sensor.zavod_garage_open_close
history:
  exclude:
    entities:
      - automation.garage_door_couter
      - counter.garage_counter
      - input_boolean.garage_door_direction
      - input_boolean.garage_door_motion
      - script.garage_counter_decrement
      - script.garage_counter_increment
      - script.garage_door_direction
      - script.garagescript
      - sensor.garage_open_close
      - automation.kalibrovka_otkryty
      - automation.kalibrovka_zakryty
      - automation.smena_napravleniia
      - script.noop
      - script.zavod_garagescript
      - counter.zavod_garage_counter
      - input_boolean.zavod_garage_door_direction
      - input_boolean.zavod_garage_door_motion
      - script.zavod_garage_counter_decrement
      - script.zavod_garage_counter_increment
      - script.zavod_garage_door_direction
      - sensor.zavod_garage_open_close

xiaomi_gateway3:
  buzzer: off
  debug: true
  devices:
    "0x158d00039db890":
      occupancy_timeout: 10
    "0x158d0003983bf4":
      occupancy_timeout: 10
    "0x158d0003966333":
      occupancy_timeout: 10
    "0x158d000396635b":
      occupancy_timeout: 10
    "0x158d0002583b1a":
      occupancy_timeout: 10
    "0x158d0003f12cf9":
      occupancy_timeout: 10
    "0x158d000398f96c":
      occupancy_timeout: 10

remote_homeassistant:
  instances:
    - host: 192.168.88.128
      port: 8123
      secure: false
      verify_ssl: true
      access_token: !secret access_token_ha_128
      entity_prefix: "zavod_"
      include:
        domains:
          - sensor
          - switch
          - binary_sensor
          - media_player
          - remote
        entities:
          - script.garagescript
          - counter.garage_counter
          - input_boolean.garage_door_direction
          - input_boolean.garage_door_motion
          - script.garage_counter_decrement
          - script.garage_counter_increment
          - script.garage_door_direction
