homeassistant:
  name: Home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 72
  unit_system: metric
  time_zone: Asia/Yekaterinburg
  country: RU
  customize: !include customize.yaml
  packages: !include_dir_merge_named includes/packages
  allowlist_external_dirs:
    - "/config"
    - "/tmp"
    - "/share"

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

api:

websocket_api:

mobile_app:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 192.168.88.0/24
    - 172.22.0.0/24
#    - 127.0.0.1

mqtt:
  sensor:
    - name: Bridge state
      state_topic: "zigbee2mqtt/bridge/state"
      icon: mdi:router-wireless

#Вынос во внешние файлы
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
light: !include includes/light.yaml
notify: !include notify.yaml
input_number: !include includes/input_number.yaml
lovelace: !include includes/lovelace.yaml
automation old: !include automations.yaml
switch: !include includes/switch.yaml
#klipper: !include includes/klipper.yaml
alert: !include includes/alert.yaml
utility_meter: !include includes/utility_meter.yaml

#Вынос во внешние папки
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
binary_sensor: !include_dir_merge_list includes/binary_sensor
template: !include_dir_merge_list includes/templates

remote:
  - platform: xiaomi_miio
    name: mi_remote
    host: 192.168.88.40
    token: 86cce819993f3bc5074c841e53fac3ce

yandex_station:
  username: igorponomarev1986
  password: password_yandex
  include:
    - media_player.samsung_tv_zal
    - media_player.tv_kukhnia

# yandex_smart_home:
#   notifier:
#     - oauth_token: !secret yandex_oauth_token
#       skill_id: !secret yandex_skill_id
#       user_id: !secret ha_user_id

wake_on_lan:

smartir:

#Media Players
media_player:
  - platform: smartir
    name: Samsung tv zal
    unique_id: samsung_tv_zal
    device_code: 2000
    controller_data: remote.mi_remote
    power_sensor: binary_sensor.tv_zal_status #откуда считывать состояния устройства, например с умной розетки

  - platform: smartir
    name: LG tv spalnya
    unique_id: lg_tv_spalnya
    device_code: 1040
    controller_data: remote.ir_broadlink_remote
    power_sensor: binary_sensor.tv_spalnya_status #откуда считывать состояния устройства, например с умной розетки

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_allowed_chat_id1
      - !secret telegram_bot_allowed_chat_id2
      - !secret telegram_bot_allowed_chat_id3

xiaomi_gateway3:
  devices:
    "0x158d00039db890":
      occupancy_timeout: 1
    "0x00158d0003983bf4":
      occupancy_timeout: 1
    "0x158d0003966333":
      occupancy_timeout: 1
    "0x00158d000396635b":
      occupancy_timeout: 1
    "0x00158d0002583b1a":
      occupancy_timeout: 1
    "0x00158d0003f12cf9":
      occupancy_timeout: 1
    "0x00158d000398f96c":
      occupancy_timeout: 1

counter:

start_time:

ios:

sun:

shell_command:
  reboot_vps_pq: 'ssh root@45.14.245.69 "sudo reboot"'

logbook:
  exclude:
    entities:
      - automation.garage_door_couter
      - counter.garage_counter
      - input_boolean.garage_door_direction
      - input_boolean.garage_door_motion
      - script.garage_counter_decrement
      - script.garage_counter_increment
      - script.garage_door_direction
      - script.garagescript
      - sensor.garage_open_close
      - automation.kalibrovka_otkryty
      - automation.kalibrovka_zakryty
      - automation.smena_napravleniia
      - script.noop
      - script.zavod_garagescript
      - counter.zavod_garage_counter
      - input_boolean.zavod_garage_door_direction
      - input_boolean.zavod_garage_door_motion
      - script.zavod_garage_counter_decrement
      - script.zavod_garage_counter_increment
      - script.zavod_garage_door_direction
      - sensor.zavod_garage_open_close
history:
  exclude:
    entities:
      - automation.garage_door_couter
      - counter.garage_counter
      - input_boolean.garage_door_direction
      - input_boolean.garage_door_motion
      - script.garage_counter_decrement
      - script.garage_counter_increment
      - script.garage_door_direction
      - script.garagescript
      - sensor.garage_open_close
      - automation.kalibrovka_otkryty
      - automation.kalibrovka_zakryty
      - automation.smena_napravleniia
      - script.noop
      - script.zavod_garagescript
      - counter.zavod_garage_counter
      - input_boolean.zavod_garage_door_direction
      - input_boolean.zavod_garage_door_motion
      - script.zavod_garage_counter_decrement
      - script.zavod_garage_counter_increment
      - script.zavod_garage_door_direction
      - sensor.zavod_garage_open_close
