# Сенсор автоотключения света детская
- platform: template
  sensors:
    auto_off_svet_detskay:
      friendly_name: "Автоотключение света детская"
      value_template: >-
        {{ is_state('switch.0x00158d0006b1fada_channel_1', 'on')  
          and is_state('binary_sensor.0x158d00039db890_motion', 'off')  }}
      icon_template: >-
        {% if is_state("binary_sensor.auto_off_svet_detskay", "on") %}
        mdi:timer
        {% else %}
        mdi:timer-off
        {% endif %}

# Сенсор автоотключения света детская
- platform: template
  sensors:
    auto_off_svet_detskay_2:
      friendly_name: "Автоотключение света детская"
      value_template: >-
        {{ is_state('switch.0x00158d0006b1fada_channel_2', 'on')  
          and is_state('binary_sensor.0x158d00039db890_motion', 'off')  }}
      icon_template: >-
        {% if is_state("binary_sensor.auto_off_svet_detskay_2", "on") %}
        mdi:timer
        {% else %}
        mdi:timer-off
        {% endif %}

# Сенсор автоотключения света
- platform: template
  sensors:
    auto_off_nochnik_detskay:
      friendly_name: "Автоотключение ночника в детской"
      value_template: >-
        {{ is_state('light.zesp_bulb_00158d00036391d8', 'on')  
          and is_state('binary_sensor.0x00158d0003983bf4_motion', 'off')  }}
      icon_template: >-
        {% if is_state("binary_sensor.auto_off_nochnik_detskay", "on") %}
        mdi:timer
        {% else %}
        mdi:timer-off
        {% endif %}
